### ISSUE TITLE
Context for Entry ID?

### ISSUE THREAD

**Issue by daltonrooney** [vaersaagod/matrixmate#13]
I'm sure this could be accomplished with an advanced PHP configuration, but I'm wondering how hard it would be to add Entry ID as a context? Sometimes we have one-off feature blocks for a specific page, but otherwise the template isn't different enough to warrant its own entry type.

**Comment by daltonrooney** [comment]
@mmikkel I definitely understand that this is an edge case and the need to avoid additional complexity in the plugin. I'm curious to hear your thoughts on why this would be a bad practice, though? 

My other thought for adding in these one-off custom features inline with a matrix would be to add some kind of shortcode functionality, which has drawbacks of it's own.

**Comment by mmikkel** [comment]
@daltonrooney In my opinion it's a bad practice because individual entries, compared to Entry Types or Single sections, are by nature much more ephemeral, so it never made sense to me to have hard coded logic (or config) dependant on a particular entry ID. Since entries are more easily disposed of than Sections and Entry Types, there's a good chance you'll end up with dead code at some point (and you/your fellow team members) might not even be aware of it, at that point.

That said, here's one way to do it:

```php
<?php

if (!Craft::$app->getRequest()->getIsCpRequest()) {
    return [];
}

$entryId = null;
$segments = Craft::$app->getRequest()->getSegments();
if ($segments[2] ?? null && $segments[0] === 'entries') {
    preg_match('/^\d*/', $segments[2], $matches);
    $entryId = !empty($matches) ? $matches[0] : null;
}

return [
    'fields' => [
        'anAwesomeMatrixField' => [
            '*' => $entryId == 95 ? [
                'types' => [
                    'text' => [
                        ...
                    ],
                ],
            ] : [],
        ],
    ],
];
```
