### ISSUE TITLE
Add border of titlebar

### ISSUE THREAD

**Issue by umkasanki** [vaersaagod/matrixmate#15]
Hello.
Could you add a little border of titlebar to improve the visual structuring of the tabbed matrix block?

Maybe something like this:
`border-bottom: 1px solid rgba(51, 64, 77, 0.1)`

Result:
![изображение](https://user-images.githubusercontent.com/496132/74585044-c936af80-4fe9-11ea-8002-83c7b1abe1ed.png)

Thanks for great plugin!

**Comment by mmikkel** [comment]
Hi @umkasanki, thanks a ton for contributing!

P&T removed that border from the titlebar very recently (Craft 3.4.5); I hadn't noticed before this issue made me aware of it, so thank you for the heads up and the PR!

I just published [MatrixMate 1.2.4](https://github.com/vaersaagod/matrixmate/releases/tag/v1.2.4) which includes your CSS fix. I'm not merging the actual PR because I opted to only add the border to block types actually using MatrixMate tabs (so a different classname made more sense).
