### ISSUE TITLE
Cloning matrix block doesn't show tabs

### ISSUE THREAD

**Issue by Joorren** [vaersaagod/matrixmate#32]
### Description
When you clone an existing matrix block ([Smith](https://github.com/verbb/smith) feature), the matrix block gets cloned, but the fields inside the newly created matrix block won't get divided into their associated tabs. This makes the matrix block messy and cluttered.

### Preview
https://user-images.githubusercontent.com/22602428/119991569-e36f8380-bfc9-11eb-94c6-b788d099e7b1.mov

### Steps To Reproduce
1. Install Smith Plugin
2. Create matrixblock and add to section type
3. Create new entry and add matrixblock
4. Duplicate matrixblock with Smith Plugin

### Additional Information
* Craft Version: 3.6.15
* Matrixmate Version: 1.2.7
* Smith Version: 1.1.13
* PHP Version: 8.0
* MySQL Version: 8.0

**Comment by mmikkel** [comment]
I think this is something that should be fixed in Smith, not in MatrixMate. 

Most likely, the Smith plugin just needs to make sure that when it clones a block, the Matrix field's `Craft.MatrixInput` instance emits the same JavaScript event(s) that are emitted when blocks are added natively – specifically, the `blockAdded` event, which [MatrixMate listens to](https://github.com/vaersaagod/matrixmate/blob/master/src/assetbundles/matrixmate/dist/js/MatrixMate.js#L126) in order to instantiate new blocks.

**Comment by Joorren** [comment]
https://github.com/verbb/smith/issues/18
