### ISSUE TITLE
Craft 4.3.1 - Prevent loading of other elements..

### ISSUE THREAD

**Issue by wmdhosting** [vaersaagod/matrixmate#57]
I have big matrix field and this hapens.. on load..

https://user-images.githubusercontent.com/76176291/200244274-25a8f614-275b-41e4-a653-bb250a8de0d8.mp4

When i disable MatrixMate .. 

Matrix content load quite fast.. 

Any idea 

Im on last version of Matrix mate..2.1.1

**Comment by mmikkel** [comment]
It's probably one of two things:

1. Since there's so much stuff in the Matrix field, MatrixMate uses a long time to parse the field (and the existing blocks on pageload). I haven't seen that before, but I guess it's possible for very massive fields.

2. Something else is taking a long time to load or render, blocking MatrixMate from initialising the field.

If you could share a database dump + `composer.json` and `composer.lock` files, I can try to debug this to figure out what's causing the rendering delay. You can get in touch w/ me (`@mmikkel`) on the official Craft Discord to share the files if possible.

**Comment by wmdhosting** [comment]
ok. sent on discord..thx

**Comment by mmikkel** [comment]
Based on the files @wmdhosting sent me (thanks!), I've done some debugging and benchmarking. 

The delay in MatrixMate initialising on your "Page Builder" field is primarily due to point 2) above. There is so much stuff going on in your edit page (tons of plugins, blocks, nested fields etc) that it takes a long time (about 5-6 seconds, testing on my Mac) before the browser even has a chance to initialise the core Matrix input, which in turn initialises MatrixMate.

(Once the core Matrix input is finally constructed, MatrixMate spends about 400ms initialising – which isn't great, but also not terrible, considering the amount of blocks and the complexity of your blocks' field layouts.)

I didn't dig too deep into the rendering timeline, so unfortunately I can't point to any one specific thing impacting the performance for your edit page. But, I did experiment with disabling a few other plugins, and disabling ButtonBox especially had a very noticeable impact.

In conclusion: I'll have a think on whether MatrixMate can reliably be initialised _before_ the core Matrix JS is initialised (a thing that happens late in the pageload lifecycle, typically after all the JS for plugins and sub fields has been executed), as well as whether MatrixMate's own rendering time can be optimised for very complex Matrix fields. But, the I believe that the ultimate issue here is that the Craft UI generally doesn't scale too well with the amount of inputs in your page builder.

Finally, this did help me track down a bug in MatrixMate, where it actually attempts to initialise on Matrix fields nested inside SuperTable fields. It's not supposed to do that, as MatrixMate doesn't support nested Matrix fields. This happens _after_ the main/outer Matrix field has been initialised though, so this wouldn't actually have an effect on the perceived load time for your "Page Builder" field. Regardless, I'll have a fix out for that bug soon.

**Comment by wmdhosting** [comment]
OK, thank you very much for info. 
Will do more testing.. with all plugins..
