### ISSUE TITLE
When you have more than a few tabs, at narrow screen sizes, the tabs bust the UI

### ISSUE THREAD

**Issue by johnwbaxter** [vaersaagod/matrixmate#67]
When you bring the width of the editor down (for example when using live preview on a smaller screen), if you have a few tabs, it all overlaps each other. See screenshot below:

![image](https://github.com/vaersaagod/matrixmate/assets/338729/58030f38-3845-4a85-bdd2-59c681e395ba)

It gets worse when you get even narrower, with this many tabs!

![image](https://github.com/vaersaagod/matrixmate/assets/338729/d4adb4f2-285c-4ab7-8bb2-d54ea88ea1b4)

It's far from ideal, but you can get round this if you inject you tabs a smidge further up the dom and then someone like me with this very specific issue can add css cp that changes the tabs position from absolute to relative...but I'm sure there is a better solution!

![image](https://github.com/vaersaagod/matrixmate/assets/338729/a970c3d9-bed2-4d03-9166-d46a8b97fd8d)

**Comment by johnwbaxter** [comment]
Cool, cheers @mmikkel !!

**Comment by mmikkel** [comment]
Update: I've taken a closer look at this; there's no quick fix and since there are multiple problems with the current implementation of block tabs I've decided to rework how they are implemented from scratch, to increase accessibility overall. I can't give an ETA for that update but will make sure to accommodate the use case where the total width of the tabs is wider than the available horizontal space.

**Comment by mmikkel** [comment]
I mean, you presented a quick fix. But that would only kick the bucket a bit further down the road; I think a proper solution would either collapse the tabs into a disclosure menu, or make them horizontally scrollable. I'm leaning towards a disclosure menu because that would probably be the most consistent in terms of the overall Craft CP UI, but I'm very open for opinions as to which of those options would feel like the better (and most accessible) UX.

**Comment by johnwbaxter** [comment]
@mmikkel Hey man, any news on this one? Could we sponsor this feature in some way if that helps?

**Comment by mmikkel** [comment]
Hi @johnwbaxter, I haven't had the time to look into this one yet – will update this issue when there's something to report. And thank you for the offer; I'm not really interested in that but I'll try my best to make this a priority, as soon as I have some available time.

**Comment by johnwbaxter** [comment]
Hey @mmikkel, ok no worries, thank you :)

**Comment by mmikkel** [comment]
Considering MatrixMate is retired for Craft 5, I've decided to not put any significant time into the plugin at this point beyond making sure things "mostly work" for Craft 4 until its EOL. Sorry!

**Comment by johnwbaxter** [comment]
@mmikkel Ok, understood, thanks!
