### ISSUE TITLE
Craft 5 Version

### ISSUE THREAD

**Issue by CreateSean** [vaersaagod/matrixmate#72]
Do you have plans to release a craft 5 compatible version?

**Comment by mmikkel** [comment]
Honestly, still undecided – but I'm leaning strongly towards retiring the plugin for Craft 5.

The fact is that Craft 5.0 makes MatrixMate almost completely redundant:

* Block tabs: natively supported via entry types
* Hidden block types per section/category/etc: as entry types are decoupled in Craft 5, you achieve basically the same result by creating multiple Matrix fields and mix'n'match different entry types inside them
* Hidden fields per block type: conditional support for inline Matrix fields should cover this.

To my mind, the only important feature in MatrixMate that _isn't_ covered by Craft 5.0 is the ability to *group* block/entry types on a contextual basis. However, such a feature [was discussed during the beta](https://github.com/craftcms/cms/discussions/14179#discussioncomment-8312309), so FWIW it's on P&T's radar and maybe we'll see something like it added in a 5.x release.

IMO, continuing to support features that are basically just different ways to do something that is now possible in core, is not a sensible way forward. So, if we did port MatrixMate to Craft 5, it'd necessarily be a very different plugin; basically all we'd keep is the grouping feature, and even that I would probably implement similarly to [how P&T would likely implement this feature](https://github.com/craftcms/cms/discussions/14179#discussioncomment-8312951), i.e. "headings within the single disclosure menu". Not because that sounds like an objectively better UX vs. distinct disclosure menus per type group, but because I think _designing for redundancy_ is the most sensible approach for plugins like MatrixMate.

As far as existing sites go – I totally get that _upgrading_ sites that are dependent on MatrixMate for wrangling huge mega-Matrixes, is probably not going to be fun 😬 The silver lining is that the new content architecture in Craft 5 should make it relatively simple to actually move Matrix entries (nee blocks) from one Matrix field to another – which paves the way for a migration path where bigger Matrix fields can be "split" into different, smaller Matrix fields, sharing (some of) the same entry types. I know that a potential CLI command for moving entries to a different _section_ has been talked about, so it would make sense that something similar becomes available to Matrix entries in one way or another. However this shakes out, Craft 4 isn't EOL until April 2026, so I don't believe anyone should be in a huge rush to upgrade (especially anyone with massive mega-Matrixes 😓) just yet 🙂

**Comment by mmikkel** [comment]
Probably not a huge surprise, but I decided that MatrixMate is definitely not being updated to work on Craft 5.

At some point, I might (strong emphasis on _might_) look into creating some sort of utility/migration to help convert MatrixMate configs to discrete Matrix fields with the proper distribution of entry types.

Big thanks for the interest in this little plugin over the years, all the PRs and bug reports ❤️

**Comment by lindseydiloreto** [comment]
I fully respect that decision, we retired Spoon for the exact same reasons. 🙏

**Comment by anita-chouhan** [comment]
Hi @mmikkel, curious about your plans for the utility/migration to convert _MatrixMate_ configs to discrete Matrix fields plugin. Is there anything planned for the near future?

**Comment by masiorama** [comment]
+1 for the utility/migration feature, if it will come eventually. Thanks!
